### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Khanggggggggggg** [SealedSaucer/Colorcord#2]
DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/runner/Colorcord/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'patch',
  path: '/guilds/951024668402388994/roles/964222547816247336',
  code: 50013,
  httpStatus: 403
}

**Comment by SealedSaucer** [comment]
Make sure the bot's role is above all other roles.
